version: "3.9"
services:


  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=amikom_pedia

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT_APP=8081
      - DB_DSN=postgres://root:root@172.17.0.3:5432/amikompedia?sslmode=disable
      - APP_NAME=BeneWeb
      - GO_ENV=DEV
      - TOKEN_SYMETRIC_KEY=msfwvvokev71979lkfoqjipld97802jw
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
